### ISSUE TITLE
how do i open the gui

### ISSUE THREAD

**Issue by omegabr22** [cookiedragon234/Luchadora#3]
i keeping pressing p and it dont work

**Comment by cookiedragon234** [comment]
Press escape, and click mods, and make sure that it is actually loaded. Also check .minecraft/mods and make sure both the dependencies and release jars are there.

**Comment by omegabr22** [comment]
its there both are there and the mod is loaded

**Comment by cookiedragon234** [comment]
Have you tried looking in the logs (`.minecraft/logs/latest.log`) and seeing if there are any errors or anything printed to the console? Also check if you are able to use commands, like `.t Gui`

**Comment by omegabr22** [comment]
ok i checked the logs and none of the modules has binds

**Comment by cookiedragon234** [comment]
as you can see here: https://github.com/cookiedragon234/Luchadora/blob/master/src/main/java/cookiedragon/luchadora/module/impl/ui/elements/clickgui/GuiModule.java#L14 the Gui module has a default keybind of P, which should be assigned to it on startup. 
This works fine for me. Not sure why it wouldnt work for you. 
If there definately werent any other errors/messages in the console related to this then Ill add this to my todo and debug it at a later date. A temporary fix will be to add commands, such as `.t` and `.bind`.
